// Starter templates — one tap to a viral-looking layout the user can tweak.

import { CANVAS_W, CANVAS_H, Scene, uid } from "./types";

export interface Template {
  id: string;
  name: string;
  build: () => Scene;
}

export const TEMPLATES: Template[] = [
  {
    id: "mrbeast",
    name: "MEGA",
    build: () => ({
      background: { type: "gradient", from: "#ff512f", to: "#dd2476", angle: 120 },
      layers: [
        {
          id: uid(),
          type: "text",
          text: "BUNU\nİZLE!",
          x: CANVAS_W / 2,
          y: CANVAS_H / 2,
          rotation: -4,
          fontSize: 190,
          color: "#ffffff",
          strokeColor: "#000000",
          strokeWidth: 12,
          fontFamily: "Anton, sans-serif",
          fontWeight: 400,
          uppercase: true,
          shadow: true,
          highlight: null,
        },
        {
          id: uid(),
          type: "emoji",
          char: "🔥",
          x: 180,
          y: 180,
          rotation: -10,
          size: 170,
        },
        {
          id: uid(),
          type: "emoji",
          char: "🤯",
          x: CANVAS_W - 180,
          y: CANVAS_H - 170,
          rotation: 10,
          size: 170,
        },
      ],
    }),
  },
  {
    id: "shock",
    name: "ŞOK",
    build: () => ({
      background: { type: "gradient", from: "#0f2027", to: "#2c5364", angle: 90 },
      layers: [
        {
          id: uid(),
          type: "shape",
          shape: "circle",
          x: CANVAS_W - 230,
          y: 230,
          rotation: 0,
          width: 300,
          height: 300,
          color: "#ffd200",
        },
        {
          id: uid(),
          type: "text",
          text: "İNANILMAZ",
          x: CANVAS_W / 2,
          y: CANVAS_H / 2 - 60,
          rotation: 0,
          fontSize: 150,
          color: "#ffd200",
          strokeColor: "#000000",
          strokeWidth: 10,
          fontFamily: "'Archivo Black', sans-serif",
          fontWeight: 400,
          uppercase: true,
          shadow: true,
          highlight: null,
        },
        {
          id: uid(),
          type: "text",
          text: "SONUÇ",
          x: CANVAS_W / 2,
          y: CANVAS_H / 2 + 110,
          rotation: 0,
          fontSize: 110,
          color: "#ffffff",
          strokeColor: "#e50914",
          strokeWidth: 8,
          fontFamily: "'Archivo Black', sans-serif",
          fontWeight: 400,
          uppercase: true,
          shadow: true,
          highlight: null,
        },
      ],
    }),
  },
  {
    id: "vs",
    name: "VS",
    build: () => ({
      background: { type: "gradient", from: "#360033", to: "#0b8793", angle: 0 },
      layers: [
        {
          id: uid(),
          type: "text",
          text: "VS",
          x: CANVAS_W / 2,
          y: CANVAS_H / 2,
          rotation: 0,
          fontSize: 260,
          color: "#ff3b3b",
          strokeColor: "#ffffff",
          strokeWidth: 14,
          fontFamily: "Anton, sans-serif",
          fontWeight: 400,
          uppercase: true,
          shadow: true,
          highlight: null,
        },
        {
          id: uid(),
          type: "text",
          text: "A TAKIMI",
          x: 260,
          y: 90,
          rotation: -3,
          fontSize: 70,
          color: "#ffffff",
          strokeColor: "#000000",
          strokeWidth: 6,
          fontFamily: "'Bebas Neue', sans-serif",
          fontWeight: 400,
          uppercase: true,
          shadow: true,
          highlight: "#1d9bf0",
        },
        {
          id: uid(),
          type: "text",
          text: "B TAKIMI",
          x: CANVAS_W - 260,
          y: CANVAS_H - 90,
          rotation: 3,
          fontSize: 70,
          color: "#ffffff",
          strokeColor: "#000000",
          strokeWidth: 6,
          fontFamily: "'Bebas Neue', sans-serif",
          fontWeight: 400,
          uppercase: true,
          shadow: true,
          highlight: "#e50914",
        },
      ],
    }),
  },
  {
    id: "clean",
    name: "TEMİZ",
    build: () => ({
      background: { type: "solid", color: "#0a0a0f" },
      layers: [
        {
          id: uid(),
          type: "shape",
          shape: "rect",
          x: 40,
          y: CANVAS_H / 2,
          rotation: 0,
          width: 16,
          height: 420,
          color: "#e50914",
        },
        {
          id: uid(),
          type: "text",
          text: "Başlığını\nburaya yaz",
          x: CANVAS_W / 2 + 30,
          y: CANVAS_H / 2,
          rotation: 0,
          fontSize: 120,
          color: "#ffffff",
          strokeColor: "#000000",
          strokeWidth: 0,
          fontFamily: "Montserrat, sans-serif",
          fontWeight: 900,
          uppercase: false,
          shadow: false,
          highlight: null,
        },
      ],
    }),
  },
];

export function blankScene(): Scene {
  return {
    background: { type: "gradient", from: "#1e3c72", to: "#2a5298", angle: 120 },
    layers: [
      {
        id: uid(),
        type: "text",
        text: "VIRAL\nBAŞLIK",
        x: CANVAS_W / 2,
        y: CANVAS_H / 2,
        rotation: 0,
        fontSize: 170,
        color: "#ffffff",
        strokeColor: "#000000",
        strokeWidth: 10,
        fontFamily: "Anton, sans-serif",
        fontWeight: 400,
        uppercase: true,
        shadow: true,
        highlight: null,
      },
    ],
  };
}
